<img src="../../../aulas/notebooks/imgs/unifor_logo.png" width="400">
<br>
<b>
<font size="6" face="arial" color="blue">
    Graduação em Ciência da Computação
</font>
</b>
<br>
<b>
<font size="4" face="arial">
    Disciplina: Métodos Quantitativos para Computação
</font>
</b>

**Orientador: Prof. Me. Ricardo Carubbi** <br>
*Docente da Graduação e Pós-Graduação em Ciência de Dados e Inteligência Artificial*<br>
*Laboratório de Ciência de Dados e Inteligência Artificial*<br>
*Universidade de Fortaleza*<br>

<p dir="ltr" style="text-align: left;">
    <strong>Links:</strong>
    <a href="https://www2.unifor.br/controle_pesquisa/pesquisarprofessor.do?actionParameter=prepareUpdate&amp;p_tp_ambiente=2&amp;p_tp_chamada=1&amp;p_tp_apresentacao=1&amp;cdPesquisador=767686193" target="_blank">Unifor</a> |
    <a href="http://lattes.cnpq.br/5738786447903616" target="_blank">Lattes</a> |
    <a href="https://unifor.br/web/pesquisa-inovacao/ncdia" target="_blank">NCDIA</a> |
    <a href="https://github.com/carubbi/" target="_blank">Github</a>
</p>

# **Preprocessamento dos dados**

## **Importação das bibliotecas**

**Objetivo da seção**
- Carregar as bibliotecas base do pipeline de pré-processamento.

**Bibliotecas, funções e métodos usados**
- `re`: módulo para expressões regulares; ajuda a extrair padrões de
  texto, ([link](https://docs.python.org/3/library/re.html)).
- `pathlib.Path`: representa caminhos de arquivos de forma segura,
  ([link](https://docs.python.org/3/library/pathlib.html)).
- `pandas`: manipulação tabular de dados,
  ([link](https://pandas.pydata.org/docs/)).

In [1]:
# Importação das bibliotecas.
from pathlib import Path
import pandas as pd

## **Configurações Iniciais**

**Objetivo da seção**
- Definir configurações de visualização e os caminhos de entrada/saída
  do processo.

**Bibliotecas, funções e métodos usados**
- `pd.set_option(...)`: define como o notebook exibe tabelas e
  números, ([link](https://pandas.pydata.org/docs/reference/api/
  pandas.set_option.html)).
- `Path('...')`: cria objetos de caminho para leitura/gravação,
  ([link](https://docs.python.org/3/library/pathlib.html#pathlib.Path)).
- Variáveis de configuração (`INPUT_PATH`, `OUTPUT_PATH`): centralizam
  rotas do fluxo e evitam caminhos fixos espalhados no código.

In [2]:
# Configuração de visualização no notebook.
pd.set_option('display.max_columns', 120)
pd.set_option('display.float_format', lambda x: f'{x:,.4f}')

# Define o caminho do dataset bruto de entrada e final após pré-processamento.
INPUT_PATH = Path('../../dataset/nba_stats.csv')
OUTPUT_PATH = Path('../../dataset/nba_stats_preprocessed.csv')

In [4]:
# Ative SAVE_OUTPUT para gravar o CSV final.
SAVE_OUTPUT = True

## **Carregamento do Dataset**

**Objetivo da seção**
- Ler o CSV original e criar uma cópia de trabalho.

**Bibliotecas, funções e métodos usados**
- `pd.read_csv(...)`: lê arquivo CSV para `DataFrame`, ([link](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)).
- `df.copy()`: cria cópia para preservar o dado bruto, ([link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html)).
- `df.head(n)`: mostra amostra inicial para inspeção, ([link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html)).
- `df.shape`: retorna número de linhas e colunas, ([link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html)).

In [3]:
# Lê o CSV original e cria uma cópia de trabalho.
df_raw = pd.read_csv(INPUT_PATH, dtype=str)
df = df_raw.copy()

# Exibe dimensões iniciais e as primeiras linhas para validação visual.
print(f'Shape original: {df.shape}')
df.head(3)

Shape original: (8162, 55)

,year,name,playerId,playerSlug,positionId,teamId,status,gamesPlayed,avgMinutes,avgFouls,flagrantFouls,technicalFouls,ejections,doubleDouble,tripleDouble,minutes,rebounds,fouls,avgRebounds,avgPoints,avgFieldGoalsMade,avgFieldGoalsAttempted,fieldGoalPct,avgThreePointFieldGoalsMade,avgThreePointFieldGoalsAttempted,threePointFieldGoalPct,avgFreeThrowsMade,avgFreeThrowsAttempted,freeThrowPct,avgAssists,avgTurnovers,points,fieldGoalsMade,fieldGoalsAttempted,threePointFieldGoalsMade,threePointFieldGoalsAttempted,freeThrowsMade,freeThrowsAttempted,assists,turnovers,avgSteals,avgBlocks,steals,blocks,position,birthdate,college,draftinfo,birthplace,team,experience,rankingSalary,salary,weight,height
0,1999,Allen Iverson,366,allen-iverson,SG,PHI,inactive,48.0,41.458332,2.0416667,0.0,5.0,0.0,4.0,0.0,1990.0,236.0,98.0,4.9166665,26.75,9.0625,22.0,41.19300079345703,1.2083334,4.1458335,29.145729541778564,7.4166665,9.875,75.1050033569336,4.6458335,3.4791667,1284.0,435.0,1056.0,58.0,199.0,356.0,474.0,223.0,167.0,2.2916667,0.14583333,110.0,7.0,Shooting Guard,6/7/1975,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",NaN,NaN,15,"$9,000,000",NaN,NaN
1,2000,Allen Iverson,366,allen-iverson,SG,PHI,inactive,70.0,40.75714,2.3142858,0.0,12.0,0.0,1.0,0.0,2853.0,267.0,162.0,3.8142858,28.414286,10.414286,24.757143,42.06600189208984,1.2714286,3.7285714,34.09961760044098,6.3142858,8.857142,71.29000091552734,4.6857142,3.2857144,1989.0,729.0,1733.0,89.0,261.0,442.0,620.0,328.0,230.0,2.057143,0.071428575,144.0,5.0,Shooting Guard,6/7/1975,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",NaN,NaN,27,"$10,125,000",NaN,NaN
2,2001,Allen Iverson,366,allen-iverson,SG,PHI,inactive,71.0,41.957745,2.0704226,0.0,18.0,0.0,4.0,0.0,2979.0,273.0,147.0,3.8450704,31.084507,10.732394,25.535212,42.02999877929688,1.3802817,4.3098593,32.02614486217499,8.239436,10.1267605,81.36299896240234,4.5774646,3.3380282,2207.0,762.0,1813.0,98.0,306.0,585.0,719.0,325.0,237.0,2.5070422,0.28169015,178.0,20.0,Shooting Guard,6/7/1975,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",NaN,NaN,17,"$11,250,000",NaN,NaN

In [10]:
# Exibe informações gerais sobre o DataFrame, tipos de dados e contagem de valores não nulos.
df.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 8162 entries, 0 to 8161
Data columns (total 55 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   year                              8162 non-null   str
 1   name                              8162 non-null   str
 2   playerId                          8162 non-null   str
 3   playerSlug                        8162 non-null   str
 4   positionId                        8156 non-null   str
 5   teamId                            8162 non-null   str
 6   status                            8162 non-null   str
 7   gamesPlayed                       8162 non-null   str
 8   avgMinutes                        8162 non-null   str
 9   avgFouls                          8162 non-null   str
 10  flagrantFouls                     8162 non-null   str
 11  technicalFouls                    8162 non-null   str
 12  ejections                         8162 non-null   str
 13  doubleDouble                      8162 non-null   str
 14  tripleDouble                      8162 non-null   str
 15  minutes                           8162 non-null   str
 16  rebounds                          8162 non-null   str
 17  fouls                             8162 non-null   str
 18  avgRebounds                       8162 non-null   str
 19  avgPoints                         8162 non-null   str
 20  avgFieldGoalsMade                 8162 non-null   str
 21  avgFieldGoalsAttempted            8162 non-null   str
 22  fieldGoalPct                      8162 non-null   str
 23  avgThreePointFieldGoalsMade       8162 non-null   str
 24  avgThreePointFieldGoalsAttempted  8162 non-null   str
 25  threePointFieldGoalPct            8162 non-null   str
 26  avgFreeThrowsMade                 8162 non-null   str
 27  avgFreeThrowsAttempted            8162 non-null   str
 28  freeThrowPct                      8162 non-null   str
 29  avgAssists                        8162 non-null   str
 30  avgTurnovers                      8162 non-null   str
 31  points                            8162 non-null   str
 32  fieldGoalsMade                    8162 non-null   str
 33  fieldGoalsAttempted               8162 non-null   str
 34  threePointFieldGoalsMade          8162 non-null   str
 35  threePointFieldGoalsAttempted     8162 non-null   str
 36  freeThrowsMade                    8162 non-null   str
 37  freeThrowsAttempted               8162 non-null   str
 38  assists                           8162 non-null   str
 39  turnovers                         8162 non-null   str
 40  avgSteals                         8162 non-null   str
 41  avgBlocks                         8162 non-null   str
 42  steals                            8162 non-null   str
 43  blocks                            8162 non-null   str
 44  position                          8162 non-null   str
 45  birthdate                         8162 non-null   str
 46  college                           6750 non-null   str
 47  draftinfo                         6977 non-null   str
 48  birthplace                        7947 non-null   str
 49  team                              2304 non-null   str
 50  experience                        2304 non-null   str
 51  rankingSalary                     8162 non-null   str
 52  salary                            8162 non-null   str
 53  weight                            2304 non-null   str
 54  height                            2304 non-null   str
dtypes: str(55)
memory usage: 3.4 MB

## **Pré-processamento dos Dados**

**Objetivo da seção**
- Executar limpeza, padronização e transformação das variáveis.

### **Validação e Transformações**

**Objetivo da seção**
- Garantir consistência estrutural e aplicar conversões para análise.

#### **Validação estrutural**

In [33]:
# Define colunas mínimas para o pipeline.
required_cols = [
    'year', 'name', 'playerId', 'teamId', 'positionId', 'status',
    'salary', 'birthdate', 'height', 'weight', 'experience'
]
print(f'Colunas: {required_cols}')

Colunas: ['year', 'name', 'playerId', 'teamId', 'positionId', 'status', 'salary', 'birthdate', 'height', 'weight', 'experience']

In [34]:
# Define chave de unicidade por temporada/jogador/time.
key_cols = ['year', 'playerId', 'teamId']

# Conta duplicidade pela chave de unicidade.
dup_key = df.duplicated(subset=key_cols).sum()

# Conta duplicidade de linha completa.
dup_full = df.duplicated().sum()

# Define quantas colunas faltantes principais exibir.
top_n = 15

# Reporta duplicidades e faltantes principais.
print('Duplicidades (linha completa):', dup_full)
print(f'Duplicidades por chave {key_cols}:', dup_key)
print(f'Faltantes (top {top_n}):')
display(df.isna().sum().sort_values(ascending=False).head(top_n))

Duplicidades (linha completa): 0
Duplicidades por chave ['year', 'playerId', 'teamId']: 0
Faltantes (top 15):

height                           5858
experience                       5858
weight                           5858
team                             5858
college                          1412
draftinfo                        1185
birthplace                        215
positionId                          6
points                              0
assists                             0
avgTurnovers                        0
fieldGoalsMade                      0
fieldGoalsAttempted                 0
threePointFieldGoalsMade            0
threePointFieldGoalsAttempted       0
dtype: int64

#### **Limpeza básica de textos e normalização de faltantes**

In [35]:
# Identifica colunas textuais para tratamento padronizado.
str_cols = df.select_dtypes(include=['object', 'str']).columns.tolist()

# Remove espaços extras nas extremidades.
for col in str_cols:
    df[col] = df[col].astype('string').str.strip()

# Define marcadores textuais de ausência.
missing_tokens = {'', 'NA', 'N/A', 'null', 'None', '-'}

# Converte marcadores para NA do pandas.
for col in str_cols:
    df[col] = df[col].replace(list(missing_tokens), pd.NA)

# Informa quantidade de colunas textuais tratadas.
print('Colunas textuais tratadas:', len(str_cols))

Colunas textuais tratadas: 55

#### **Correção de inconsistência**

In [36]:
# Detecta casos em que altura veio em libras.
height_has_lbs = df['height'].astype('string').str.contains(
    r'lbs', case=False, na=False
)
print('Registros com "lbs" em height:', height_has_lbs.sum())
print(df['height'].dropna().head())

Registros com "lbs" em height: 2304
1469    218 lbs
1470    218 lbs
1471    218 lbs
1472    218 lbs
1473    218 lbs
Name: height, dtype: string

In [37]:
# Detecta casos em que peso veio em pés/polegadas.
weight_has_feet = df['weight'].astype('string').str.contains(
    r"\d+'\s*\d+\"", na=False
)
print('Registros com formato feet/inches em weight:', weight_has_feet.sum())
print(df['weight'].dropna().head())

Registros com formato feet/inches em weight: 2304
1469    6' 8"
1470    6' 8"
1471    6' 8"
1472    6' 8"
1473    6' 8"
Name: weight, dtype: string

In [38]:
# Marca linhas com possível inversão entre altura e peso.
swap_mask = height_has_lbs & weight_has_feet

# Quantifica linhas suspeitas.
swap_count = int(swap_mask.sum())
if swap_count > 0:
    # Guarda temporariamente os valores atuais.
    h_old = df.loc[swap_mask, 'height'].copy()
    w_old = df.loc[swap_mask, 'weight'].copy()
    # Executa troca de valores entre colunas.
    df.loc[swap_mask, 'height'] = w_old
    df.loc[swap_mask, 'weight'] = h_old

# Reporta o total de correções aplicadas.
print('Linhas corrigidas por inversão height/weight:', swap_count)

Linhas corrigidas por inversão height/weight: 2304

#### **Conversões tipadas**

Conversões de tipo sem criação de novas variáveis analíticas.

**Métodos usados nesta subseção**
- `pd.to_datetime(..., errors='coerce')`: converte datas e preserva inválidos como ausentes.
- `pd.to_numeric(..., errors='coerce')`: converte números textuais e protege o fluxo contra valores inválidos.
- `.astype('Int64')`: define inteiro nullable para colunas discretas com possíveis ausências.

In [39]:
# Converte salário textual para numérico em dólar.
df['salary_usd'] = (
    df['salary']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype('Float64')
)
print('Salário convertido para numérico:', df['salary_usd'].notna().sum())
print(df[['salary', 'salary_usd']].head())

Salário convertido para numérico: 8162
        salary      salary_usd
0   $9,000,000  9,000,000.0000
1  $10,125,000 10,125,000.0000
2  $11,250,000 11,250,000.0000
3  $12,375,000 12,375,000.0000
4  $13,500,000 13,500,000.0000

In [40]:
# Converte data de nascimento para datetime.
df['birthdate_dt'] = pd.to_datetime(df['birthdate'], errors='coerce')

print('Birthdate convertido para datetime:', df['birthdate_dt'].notna().sum())
print(df[['birthdate', 'birthdate_dt']].head())

Birthdate convertido para datetime: 5858
  birthdate birthdate_dt
0  6/7/1975   1975-06-07
1  6/7/1975   1975-06-07
2  6/7/1975   1975-06-07
3  6/7/1975   1975-06-07
4  6/7/1975   1975-06-07

In [41]:
# Converte ano da temporada para tipo numérico inteiro nullable.
df['year'] = pd.to_numeric(df['year'], errors='coerce').astype('Int64')

print('Ano convertido para Int64:', df['year'].notna().sum())
print(df['year'].head())

Ano convertido para Int64: 8162
0    1999
1    2000
2    2001
3    2002
4    2003
Name: year, dtype: Int64

#### **Engenharia de variáveis**

Criação de variáveis derivadas a partir de colunas já tipadas.

**Métodos usados nesta subseção**
- Operações vetorizadas com séries pandas para derivação de variáveis.
- `str.extract(...)` para extração de componentes numéricos via regex.
- `.astype(...)` para tipagem final consistente das variáveis derivadas.

In [42]:
# Calcula idade na temporada a partir do ano já tipado e da data de nascimento.
df['age_in_season'] = (
    df['year'] - df['birthdate_dt'].dt.year
).astype('Int64')

print('Idade na temporada calculada:', int(df['age_in_season'].notna().sum()))
df['age_in_season'].head()

Idade na temporada calculada: 5858

0    24
1    25
2    26
3    27
4    28
Name: age_in_season, dtype: Int64

In [43]:
# Extrai número de anos de experiência da string original.
df['experience_years'] = (
    df['experience']
    .str.extract(r'(\d+)', expand=False)
    .astype('Int64')
)

print('Anos de experiência calculados:', int(df['experience_years'].notna().sum()))
df[['experience', 'experience_years']].dropna().head()

Anos de experiência calculados: 2237

       experience  experience_years
1469  17th Season                17
1470  17th Season                17
1471  17th Season                17
1472  17th Season                17
1473  17th Season                17

**Explicação da regex `r'(\d+)'` (experiência)**

- `r"..."`: string *raw* no Python.
- `( ... )`: grupo de captura (retorna o trecho encontrado).
- `\d+`: um ou mais dígitos consecutivos.

Na prática, extrai o número de textos como `"3 years"`, `"10"` ou `"2nd"`.
Com `expand=False`, o retorno é uma `Series` (não `DataFrame`).

In [44]:
# Extrai pés/polegadas da altura textual e converte para metros.
ht = df['height'].str.extract(
    r"(?P<ft>\d+)'\s*(?P<inch>\d+)"
)
print('Alturas com formato feet/inches extraídas:', ht.notna().all(axis=1).sum())
print(ht.dropna().head())

Alturas com formato feet/inches extraídas: 2304
     ft inch
1469  6    8
1470  6    8
1471  6    8
1472  6    8
1473  6    8

**Explicação da regex usada na extração de altura**

- `r"..."`: string *raw* no Python (evita escapes extras).
- `(?P<ft>\d+)`: grupo nomeado `ft` com 1+ dígitos (pés).
- `'`: apóstrofo literal entre pés e polegadas.
- `\s*`: zero ou mais espaços entre os blocos.
- `(?P<inch>\d+)`: grupo nomeado `inch` com 1+ dígitos (polegadas).

Exemplo: `6' 7"` resulta em `ft = 6` e `inch = 7`.

In [45]:
# Converte para metros usando fórmula: altura_m = (pés * 0.3048) + (polegadas * 0.0254)
df['height_m'] = (
    ht['ft'].astype('Float64') * 0.3048 +
    ht['inch'].astype('Float64') * 0.0254
)
print('Altura convertida para metros:', df['height_m'].notna().sum())
print(df[['height', 'height_m']].dropna().head())

Altura convertida para metros: 2304
     height  height_m
1469  6' 8"    2.0320
1470  6' 8"    2.0320
1471  6' 8"    2.0320
1472  6' 8"    2.0320
1473  6' 8"    2.0320

In [46]:
# Extrai peso em libras e converte para quilogramas.
weight_raw = pd.to_numeric(
    df['weight'].str.extract(r'(\d+)', expand=False),
    errors='coerce'
)
print('Pesos com formato numérico extraídos:', weight_raw.notna().sum())
print(weight_raw.dropna().head())

Pesos com formato numérico extraídos: 2304
1469    218
1470    218
1471    218
1472    218
1473    218
Name: weight, dtype: Int64

In [47]:
# Converte pesos em libras para kg.
df['weight_kg'] = (weight_raw * 0.45359237).astype('Float64')

print('Peso em kg calculado:', int(df['weight_kg'].notna().sum()))
df[['weight', 'weight_kg']].dropna().head()

Peso em kg calculado: 2304

       weight  weight_kg
1469  218 lbs    98.8831
1470  218 lbs    98.8831
1471  218 lbs    98.8831
1472  218 lbs    98.8831
1473  218 lbs    98.8831

In [48]:
# Preenche ausência de posição com rótulo explícito.
df['positionId'] = df['positionId'].fillna('NA_POS')

print('positionId faltante após preenchimento:', int(df['positionId'].isna().sum()))
df[['positionId']].head()

positionId faltante após preenchimento: 0

  positionId
0         SG
1         SG
2         SG
3         SG
4         SG

In [49]:
# Lista de colunas para inspeção consolidada das variáveis derivadas.
cols = [
    'year', 'salary', 'salary_usd', 'birthdate', 'birthdate_dt',
    'age_in_season', 'height', 'height_m', 'weight', 'weight_kg',
    'experience', 'experience_years'
]

df[cols].head()

,year,salary,salary_usd,birthdate,birthdate_dt,age_in_season,height,height_m,weight,weight_kg,experience,experience_years
0,1999,"$9,000,000","9,000,000.0000",6/7/1975,1975-06-07,24,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2000,"$10,125,000","10,125,000.0000",6/7/1975,1975-06-07,25,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2001,"$11,250,000","11,250,000.0000",6/7/1975,1975-06-07,26,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2002,"$12,375,000","12,375,000.0000",6/7/1975,1975-06-07,27,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2003,"$13,500,000","13,500,000.0000",6/7/1975,1975-06-07,28,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [50]:
# Exibe tipos e não nulos das colunas convertidas/derivadas.
df[cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 8162 entries, 0 to 8161
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              8162 non-null   Int64
 1   salary            8162 non-null   string
 2   salary_usd        8162 non-null   Float64
 3   birthdate         8162 non-null   string
 4   birthdate_dt      5858 non-null   datetime64[us]
 5   age_in_season     5858 non-null   Int64
 6   height            2304 non-null   string
 7   height_m          2304 non-null   Float64
 8   weight            2304 non-null   string
 9   weight_kg         2304 non-null   Float64
 10  experience        2304 non-null   string
 11  experience_years  2237 non-null   Int64
dtypes: Float64(3), Int64(3), datetime64[us](1), string(5)
memory usage: 813.1 KB

## **Controle de Qualidade**

**Objetivo da seção**
- Validar o resultado do pré-processamento com regras de qualidade.

Os métodos usados são descritos imediatamente antes de cada checagem.

### **Verificação de Duplicidade**

**Bibliotecas, funções e métodos usados nesta subseção**
- `pandas`: operações tabulares para detectar registros repetidos.
- `duplicated()` e `duplicated(subset=[...])`: detectam duplicidades total e por chave analítica.
- `sum()` em máscara booleana: quantifica ocorrências duplicadas.

In [51]:
# 5.1) Duplicidade de linhas completas
# Conta linhas exatamente repetidas.
dup_full = int(df.duplicated().sum())
print('dup_full:', dup_full)

dup_full: 0

In [52]:
# 5.2) Duplicidade por chave analítica
# Define chave de controle por temporada/jogador/time.
key = ['year', 'playerId', 'teamId']
# Conta repetições da chave definida.
dup_key = int(df.duplicated(subset=key).sum())
print('dup_key_year_player_team:', dup_key)

dup_key_year_player_team: 0

### **Dados Faltantes**

**Bibliotecas, funções e métodos usados nesta subseção**
- `pandas`: suporte a métricas de completude de dados.
- `isna().sum()`: contabiliza ausências por variável.
- `pd.Series({...})`: consolida indicadores de faltantes em estrutura tabular.

In [53]:
# 5.3) Faltantes nas variáveis derivadas
# Consolida faltantes nas colunas criadas no pré-processamento.
missing_checks = pd.Series({
    'salary_usd_missing': int(df['salary_usd'].isna().sum()),
    'birthdate_dt_missing': int(df['birthdate_dt'].isna().sum()),
    'age_in_season_missing': int(df['age_in_season'].isna().sum()),
    'height_m_missing': int(df['height_m'].isna().sum()),
    'weight_kg_missing': int(df['weight_kg'].isna().sum()),
    'experience_years_missing': int(df['experience_years'].isna().sum()),
})
missing_checks

salary_usd_missing             0
birthdate_dt_missing        2304
age_in_season_missing       2304
height_m_missing            5858
weight_kg_missing           5858
experience_years_missing    5925
dtype: int64

### **Dados Plausíveis**

**Bibliotecas, funções e métodos usados nesta subseção**
- `pandas`: aplicação de filtros vetorizados sobre variáveis derivadas.
- Operadores lógicos (`<`, `>`, `|`): definem limites de plausibilidade.
- `fillna(False)` e `sum()`: evitam contagem indevida e totalizam fora da faixa.

In [54]:
# 5.4) Faixa plausível de idade
# Conta idades fora do intervalo esperado para atletas da NBA.
age_out = int(
    ((df['age_in_season'] < 15) | (df['age_in_season'] > 50))
    .fillna(False).sum()
)
print('age_out_of_range_<15_or_>50:', age_out)

age_out_of_range_<15_or_>50: 0

In [55]:
# 5.5) Faixa plausível de altura (m)
# Conta alturas fora do intervalo plausível definido.
height_out = int(
    ((df['height_m'] < 1.65) | (df['height_m'] > 2.30))
    .fillna(False).sum()
)
print('height_out_of_range_<1.65_or_>2.30:', height_out)

height_out_of_range_<1.65_or_>2.30: 0

In [57]:
# 5.6) Faixa plausível de peso (kg)
# Conta pesos fora do intervalo plausível definido.
weight_out = int(
    ((df['weight_kg'] < 63) | (df['weight_kg'] > 155))
    .fillna(False).sum()
)
print('weight_out_of_range_<63_or_>155:', weight_out)

weight_out_of_range_<63_or_>155: 0

## **Preparação para Exportação**

**Objetivo da seção**
- Definir o recorte final de colunas e padronizar nomenclatura.

**Bibliotecas, funções e métodos usados**
- `drop(columns=...)`: remove colunas não necessárias, ([link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)).
- `startswith()`: identifica colunas que iniciam com um prefixo específico. ([link](https://docs.python.org/3/library/stdtypes.html#str.startswith)).
- `rename(columns=...)`: aplica dicionário EN -> PT-BR, ([link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)).

### **Seleção de colunas para exportação**

In [59]:
# Remove campos brutos que já possuem versão tratada.
cols_drop_export = [
    'salary',
    'birthdate',
    'height',
    'weight',
    'experience',
]

# Remove todas as colunas de média por regra do projeto.
avg_cols = [c for c in df.columns if c.startswith('avg')]
cols_drop_export = cols_drop_export + avg_cols

print('Colunas a remover na exportação:', cols_drop_export)

Colunas a remover na exportação: ['salary', 'birthdate', 'height', 'weight', 'experience', 'avgMinutes', 'avgFouls', 'avgRebounds', 'avgPoints', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgThreePointFieldGoalsMade', 'avgThreePointFieldGoalsAttempted', 'avgFreeThrowsMade', 'avgFreeThrowsAttempted', 'avgAssists', 'avgTurnovers', 'avgSteals', 'avgBlocks']

In [62]:
# Gera base de exportação com colunas filtradas.
df_export = df.drop(columns=cols_drop_export, errors='ignore').copy()

# Remove colunas sem dado (100% ausentes).
empty_cols = [c for c in df_export.columns if df_export[c].isna().all()]
df_export = df_export.drop(columns=empty_cols, errors='ignore')

# Exibe as primeiras linhas da base final para validação visual.
df_export.head(3)

,year,name,playerId,playerSlug,positionId,teamId,status,gamesPlayed,flagrantFouls,technicalFouls,ejections,doubleDouble,tripleDouble,minutes,rebounds,fouls,fieldGoalPct,threePointFieldGoalPct,freeThrowPct,points,fieldGoalsMade,fieldGoalsAttempted,threePointFieldGoalsMade,threePointFieldGoalsAttempted,freeThrowsMade,freeThrowsAttempted,assists,turnovers,steals,blocks,position,college,draftinfo,birthplace,team,rankingSalary,salary_usd,birthdate_dt,age_in_season,experience_years,height_m,weight_kg
0,1999,Allen Iverson,366,allen-iverson,SG,PHI,inactive,48.0,0.0,5.0,0.0,4.0,0.0,1990.0,236.0,98.0,41.19300079345703,29.145729541778564,75.1050033569336,1284.0,435.0,1056.0,58.0,199.0,356.0,474.0,223.0,167.0,110.0,7.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,15,"9,000,000.0000",1975-06-07,24,<NA>,<NA>,<NA>
1,2000,Allen Iverson,366,allen-iverson,SG,PHI,inactive,70.0,0.0,12.0,0.0,1.0,0.0,2853.0,267.0,162.0,42.06600189208984,34.09961760044098,71.29000091552734,1989.0,729.0,1733.0,89.0,261.0,442.0,620.0,328.0,230.0,144.0,5.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,27,"10,125,000.0000",1975-06-07,25,<NA>,<NA>,<NA>
2,2001,Allen Iverson,366,allen-iverson,SG,PHI,inactive,71.0,0.0,18.0,0.0,4.0,0.0,2979.0,273.0,147.0,42.02999877929688,32.02614486217499,81.36299896240234,2207.0,762.0,1813.0,98.0,306.0,585.0,719.0,325.0,237.0,178.0,20.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,17,"11,250,000.0000",1975-06-07,26,<NA>,<NA>,<NA>

In [63]:
# Lista colunas removidas na regra fixa + avg.
removed_cols = [c for c in cols_drop_export if c in df.columns]

# Reporta dimensões e colunas removidas.
print('Shape original:', df.shape)
print('Shape exportação:', df_export.shape)
print('Qtde colunas removidas (fixas + avg):', len(removed_cols))
print('Colunas removidas (fixas + avg):')
for col in removed_cols:
    print('-', col)

Shape original: (8162, 61)
Shape exportação: (8162, 42)
Qtde colunas removidas (fixas + avg): 19
Colunas removidas (fixas + avg):
- salary
- birthdate
- height
- weight
- experience
- avgMinutes
- avgFouls
- avgRebounds
- avgPoints
- avgFieldGoalsMade
- avgFieldGoalsAttempted
- avgThreePointFieldGoalsMade
- avgThreePointFieldGoalsAttempted
- avgFreeThrowsMade
- avgFreeThrowsAttempted
- avgAssists
- avgTurnovers
- avgSteals
- avgBlocks

In [65]:
# 6.1) Dicionário EN -> PT-BR (termos técnicos NBA)
# Define mapeamento de nomes para padrão PT-BR da disciplina.
rename_cols_pt_nba = {
    'year': 'temporada',
    'name': 'nome_jogador',
    'playerId': 'id_jogador',
    'playerSlug': 'id_url_jogador',
    'positionId': 'sigla_posicao',
    'teamId': 'sigla_time',
    'status': 'status_jogador',
    'gamesPlayed': 'jogos_disputados',
    'flagrantFouls': 'faltas_flagrantes',
    'technicalFouls': 'faltas_tecnicas',
    'ejections': 'expulsoes',
    'doubleDouble': 'duplo_duplo',
    'tripleDouble': 'triplo_duplo',
    'minutes': 'minutos_totais',
    'rebounds': 'rebotes',
    'fouls': 'faltas',
    'fieldGoalPct': 'pct_arremessos_quadra',
    'threePointFieldGoalPct': 'pct_bolas_3',
    'freeThrowPct': 'pct_lances_livres',
    'points': 'pontos',
    'fieldGoalsMade': 'arremessos_quadra_convertidos',
    'fieldGoalsAttempted': 'arremessos_quadra_tentados',
    'threePointFieldGoalsMade': 'bolas_3_convertidas',
    'threePointFieldGoalsAttempted': 'bolas_3_tentadas',
    'freeThrowsMade': 'lances_livres_convertidos',
    'freeThrowsAttempted': 'lances_livres_tentados',
    'assists': 'assistencias',
    'turnovers': 'perdas_bola',
    'steals': 'roubos_bola',
    'blocks': 'tocos',
    'position': 'posicao',
    'college': 'universidade',
    'draftinfo': 'informacoes_recrutamento',
    'birthplace': 'local_nascimento',
    'team': 'nome_time',
    'rankingSalary': 'ranking_salarial',
    'salary_usd': 'salario_usd',
    'birthdate_dt': 'data_nascimento',
    'age_in_season': 'idade_temporada',
    'height_m': 'altura_m',
    'weight_kg': 'peso_kg',
    'experience_years': 'anos_experiencia',
}

# Aplica somente renomeações de colunas existentes no export.
rename_applied = {}
for old, new in rename_cols_pt_nba.items():
    if old in df_export.columns:
        rename_applied[old] = new

# Renomeia colunas mantendo apenas o mapeamento válido.
df_export = df_export.rename(columns=rename_applied)

df_export.head()

,temporada,nome_jogador,id_jogador,id_url_jogador,sigla_posicao,sigla_time,status_jogador,jogos_disputados,faltas_flagrantes,faltas_tecnicas,expulsoes,duplo_duplo,triplo_duplo,minutos_totais,rebotes,faltas,pct_arremessos_quadra,pct_bolas_3,pct_lances_livres,pontos,arremessos_quadra_convertidos,arremessos_quadra_tentados,bolas_3_convertidas,bolas_3_tentadas,lances_livres_convertidos,lances_livres_tentados,assistencias,perdas_bola,roubos_bola,tocos,posicao,universidade,informacoes_recrutamento,local_nascimento,nome_time,ranking_salarial,salario_usd,data_nascimento,idade_temporada,anos_experiencia,altura_m,peso_kg
0,1999,Allen Iverson,366,allen-iverson,SG,PHI,inactive,48.0,0.0,5.0,0.0,4.0,0.0,1990.0,236.0,98.0,41.19300079345703,29.145729541778564,75.1050033569336,1284.0,435.0,1056.0,58.0,199.0,356.0,474.0,223.0,167.0,110.0,7.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,15,"9,000,000.0000",1975-06-07,24,<NA>,<NA>,<NA>
1,2000,Allen Iverson,366,allen-iverson,SG,PHI,inactive,70.0,0.0,12.0,0.0,1.0,0.0,2853.0,267.0,162.0,42.06600189208984,34.09961760044098,71.29000091552734,1989.0,729.0,1733.0,89.0,261.0,442.0,620.0,328.0,230.0,144.0,5.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,27,"10,125,000.0000",1975-06-07,25,<NA>,<NA>,<NA>
2,2001,Allen Iverson,366,allen-iverson,SG,PHI,inactive,71.0,0.0,18.0,0.0,4.0,0.0,2979.0,273.0,147.0,42.02999877929688,32.02614486217499,81.36299896240234,2207.0,762.0,1813.0,98.0,306.0,585.0,719.0,325.0,237.0,178.0,20.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,17,"11,250,000.0000",1975-06-07,26,<NA>,<NA>,<NA>
3,2002,Allen Iverson,366,allen-iverson,SG,PHI,inactive,60.0,0.0,12.0,1.0,4.0,1.0,2622.0,269.0,102.0,39.84400177001953,29.10447716712952,81.1969985961914,1883.0,665.0,1669.0,78.0,268.0,475.0,585.0,331.0,237.0,168.0,13.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,14,"12,375,000.0000",1975-06-07,27,<NA>,<NA>,<NA>
4,2003,Allen Iverson,366,allen-iverson,SG,PHI,inactive,82.0,0.0,8.0,0.0,6.0,0.0,3485.0,344.0,149.0,41.44300079345703,27.72277295589447,77.44599914550781,2262.0,804.0,1940.0,84.0,303.0,570.0,736.0,454.0,286.0,225.0,13.0,Shooting Guard,Georgetown,"1996: Rd 1, Pk 1 (PHI)","Hampton, VA",<NA>,11,"13,500,000.0000",1975-06-07,28,<NA>,<NA>,<NA>

In [66]:
# Reporta renomeações efetivamente aplicadas.
print('Qtde colunas renomeadas:', len(rename_applied))
print('Renomeacoes aplicadas:')
for old, new in rename_applied.items():
    print(f'- {old} -> {new}')

Qtde colunas renomeadas: 42
Renomeacoes aplicadas:
- year -> temporada
- name -> nome_jogador
- playerId -> id_jogador
- playerSlug -> id_url_jogador
- positionId -> sigla_posicao
- teamId -> sigla_time
- status -> status_jogador
- gamesPlayed -> jogos_disputados
- flagrantFouls -> faltas_flagrantes
- technicalFouls -> faltas_tecnicas
- ejections -> expulsoes
- doubleDouble -> duplo_duplo
- tripleDouble -> triplo_duplo
- minutes -> minutos_totais
- rebounds -> rebotes
- fouls -> faltas
- fieldGoalPct -> pct_arremessos_quadra
- threePointFieldGoalPct -> pct_bolas_3
- freeThrowPct -> pct_lances_livres
- points -> pontos
- fieldGoalsMade -> arremessos_quadra_convertidos
- fieldGoalsAttempted -> arremessos_quadra_tentados
- threePointFieldGoalsMade -> bolas_3_convertidas
- threePointFieldGoalsAttempted -> bolas_3_tentadas
- freeThrowsMade -> lances_livres_convertidos
- freeThrowsAttempted -> lances_livres_tentados
- assists -> assistencias
- turnovers -> perdas_bola
- steals -> roubos_bola
- blocks -> tocos
- position -> posicao
- college -> universidade
- draftinfo -> informacoes_recrutamento
- birthplace -> local_nascimento
- team -> nome_time
- rankingSalary -> ranking_salarial
- salary_usd -> salario_usd
- birthdate_dt -> data_nascimento
- age_in_season -> idade_temporada
- height_m -> altura_m
- weight_kg -> peso_kg
- experience_years -> anos_experiencia

### **Exportação**

In [68]:
# Se ativado, salva a versão tratada no caminho de saída.
if SAVE_OUTPUT:
    df_export.to_csv(OUTPUT_PATH, index=False)
    print(f'Arquivo salvo em: {OUTPUT_PATH.resolve()}')
else:
    print('Exportação desativada. Defina SAVE_OUTPUT = True para salvar.')

Arquivo salvo em: /Users/carubbi/Documents/aulas/T199/dataset/nba_stats_preprocessed.csv

## **Observações metodológicas**

- O pipeline **não remove linhas** por padrão, para evitar perda de
  informação sem justificativa analítica.
- As colunas originais são preservadas em `df` para rastreabilidade.
- Para exportação, usa-se `df_export` sem campos brutos não tratados:
  `salary`, `birthdate`, `height`, `weight` e `experience`.
- Para exportação, também são removidas todas as colunas com prefixo
  `avg`.
- Colunas sem dado (100% ausentes) são removidas de `df_export`.
- Antes da exportação, as colunas são renomeadas de EN -> PT-BR com
  termos técnicos da NBA.
- As medidas físicas derivadas seguem o **SI**: altura em metros
  (`altura_m`) e peso em quilogramas (`peso_kg`).